blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Join Slack
    url: 'https://logfire.pydantic.dev/docs/help/#slack'
    about: Join the Logfire Slack to ask questions, get help and chat about Pydantic AI
