name: After CI

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

permissions:
  statuses: write

jobs:
  smokeshow:
    runs-on: ubuntu-latest

    steps:
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: '3.12'

      - uses: dawidd6/action-download-artifact@v6
        with:
          workflow: ci.yml
          name: '(diff-)?coverage-html.*'
          name_is_regexp: true
          commit: ${{ github.event.workflow_run.head_sha }}
          allow_forks: true
          workflow_conclusion: completed
          if_no_artifact_found: warn

      - run: uvx smokeshow upload coverage-html
        if: hashFiles('coverage-html/*.html') != ''
        env:
          SMOKESHOW_GITHUB_STATUS_DESCRIPTION: Coverage {coverage-percentage}
          SMOKESHOW_GITHUB_COVERAGE_THRESHOLD: 95
          SMOKESHOW_GITHUB_CONTEXT: coverage
          SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SMOKESHOW_GITHUB_PR_HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
          SMOKESHOW_AUTH_KEY: ${{ secrets.SMOKESHOW_AUTH_KEY }}

      - run: uvx smokeshow upload diff-coverage-html
        if: hashFiles('diff-coverage-html/*.html') != ''
        env:
          SMOKESHOW_GITHUB_STATUS_DESCRIPTION: Diff coverage {coverage-percentage}
          SMOKESHOW_GITHUB_COVERAGE_THRESHOLD: 95
          SMOKESHOW_GITHUB_CONTEXT: diff-coverage
          SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SMOKESHOW_GITHUB_PR_HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
          SMOKESHOW_AUTH_KEY: ${{ secrets.SMOKESHOW_AUTH_KEY }}

  deploy-docs-preview:
    runs-on: ubuntu-latest
    environment:
      name: deploy-preview
      url: ${{ steps.get_preview_url.outputs.preview_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: dawidd6/action-download-artifact@v6
        with:
          workflow: ci.yml
          name: site
          path: site
          commit: ${{ github.event.workflow_run.head_sha }}
          allow_forks: true
          workflow_conclusion: completed

      - run: ls -lha

      - uses: cloudflare/wrangler-action@v3
        id: deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: previews
          workingDirectory: docs-site
          command: >
            deploy
            --var GIT_COMMIT_SHA:${{ github.event.workflow_run.head_sha }}
            --var GIT_BRANCH:${{ github.event.workflow_run.head_branch }}

      # work around for https://github.com/cloudflare/wrangler-action/issues/349
      - name: get preview URL
        id: get_preview_url
        shell: python
        run: |
          import os
          import re
          deploy_output = os.environ['DEPLOY_OUTPUT']
          m = re.search(r'https://(\S+)\.workers\.dev', deploy_output)
          assert m, f'Could not find worker URL in {deploy_output!r}'
          worker_name = m.group(1)
          m = re.search(r'Current Version ID: ([^-]+)', deploy_output)
          assert m, f'Could not find version ID in {deploy_output!r}'
          version_id = m.group(1)
          preview_url = f'https://{version_id}-{worker_name}.workers.dev'
          with open(os.environ['GITHUB_OUTPUT'], 'w') as f:
              f.write(f'preview_url={preview_url}\n')
        env:
          DEPLOY_OUTPUT: ${{ steps.deploy.outputs.command-output }}
